language: java

jdk:
  - oraclejdk7

env:
  global:
    - ANDROID_TARGET="android-19"
    - ANDROID_SDK_VERSION="22.0.1"
    - ANDROID_BUILD_TOOLS_VERSION="19.0.3"
    - GRADLE_VERSION="1.10"

#notifications:
#  email: false

before_install:
  - export BASEDIR=`pwd`

  # Fix Gradle output
  - export TERM=dumb

  # Required libs for Android build tools
  - if [ `uname -m` = x86_64 ]; then sudo apt-get update -qq; fi
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq libstdc++6:i386 lib32z1; fi

  # Android SDK
  - export FILE=android-sdk_r${ANDROID_SDK_VERSION}-linux.tgz
  - wget https://dl-ssl.google.com/android/${FILE}
  - tar -zxf ${FILE}
  - export ANDROID_HOME=${BASEDIR}/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools

  # Android Build Tools
  - export FILE=build-tools_r${ANDROID_BUILD_TOOLS_VERSION}-linux.zip
  - wget https://dl-ssl.google.com/android/repository/${FILE}
  - mkdir -p ${ANDROID_HOME}/build-tools
  - unzip -q ${FILE} -d ${ANDROID_HOME}/build-tools
  - mv ${ANDROID_HOME}/build-tools/android-4.4.2 ${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS_VERSION}

  # Install other stuff
  - echo yes | android update sdk --filter ${ANDROID_TARGET},platform-tools,extra-google-m2repository,extra-android-m2repository --force --no-ui

  # Gradle
  - export FILE=gradle-${GRADLE_VERSION}-bin.zip
  - wget http://services.gradle.org/distributions/${FILE}
  - unzip -q ${FILE}
  - export GRADLE_HOME=$BASEDIR/gradle-${GRADLE_VERSION}
  - export PATH=${PATH}:$GRADLE_HOME/bin

  - unset FILE
